### PR TITLE
Replaced all old array syntax - array() to []

### PR DESCRIPTION
**Pull request by matheusgontijo**
Replaced all old array syntax. Example:

from:
`array('debug' => true)`

to:
`['debug' => true]`

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocrm.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by matheusgontijo** [comment]
I think something is missing on [Contributor License Agreement](http://www.orocrm.com/contributor-license-agreement/) page. I would like to proceed but just can't go further.

Could you please take a further look, @anyt?

Please see the following screenshot. Thanks.

Screenshot from 2019-12-30 07-00-39

**Comment by mbessolov** [comment]
Hi @matheusgontijo,

Apparently some redirect on the website stopped working, sorry for the incovenience, we'll fix it.
You can sign the Contributor License Agreement using this link - https://oroinc.com/b2b-ecommerce/contributor-license-agreement/

Thank you for your contribution!

Thank you,
Michael

**Comment by matheusgontijo** [comment]
@mbessolov thanks for providing the link. I just filled out the form.

Looking forward to hear from Oro team about the pull request. Thanks.

**Comment by mbessolov** [comment]
@matheusgontijo, it seems that you submitted the form for **mhgontijo** GitHub username, which does not match the GitHub username you used for this pull request - **matheusgontijo**

**Comment by matheusgontijo** [comment]
@mbessolov just re-submitted. Thanks for pointing out.

Could you please take a look? Thanks, Michael.

**Comment by anyt** [comment]
Merged. Thank you for your contribution, @matheusgontijo!

**Pull request closed without merging**
